-- MySQL Script generated by MySQL Workbench
-- 05/13/17 18:08:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blesk1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blesk1` ;

-- -----------------------------------------------------
-- Schema blesk1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blesk1` DEFAULT CHARACTER SET utf8 ;
USE `blesk1` ;

-- -----------------------------------------------------
-- Table `blesk1`.`Stav`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Stav` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Stav` (
  `idStav` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `volat` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`idStav`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`Osoba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Osoba` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Osoba` (
  `idOsoba` INT NOT NULL AUTO_INCREMENT,
  `prezdivka` VARCHAR(45) NOT NULL,
  `jmeno` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NULL,
  PRIMARY KEY (`idOsoba`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`Ridic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Ridic` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Ridic` (
  `idRidic` INT NOT NULL AUTO_INCREMENT,
  `idStav` INT NULL,
  `idOsoba` INT NOT NULL,
  PRIMARY KEY (`idRidic`, `idOsoba`),
  INDEX `fk_Pracovnik_Stav1_idx` (`idStav` ASC),
  INDEX `fk_Ridic_Osoba1_idx` (`idOsoba` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`Auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Auto` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Auto` (
  `idAuto` INT NOT NULL AUTO_INCREMENT,
  `idRidic` INT NULL,
  `idVysilacka` INT NOT NULL,
  `znacka` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `barva` VARCHAR(45) NULL,
  `pocetMist` INT NULL DEFAULT 4,
  `regZnacka` VARCHAR(45) NULL,
  `taxiOdDne` DATETIME(1) NULL,
  PRIMARY KEY (`idAuto`),
  INDEX `fk_Auto_Pracovnik1_idx` (`idRidic` ASC),
  UNIQUE INDEX `idVysilacka_UNIQUE` (`idVysilacka` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`Adresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Adresa` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Adresa` (
  `idAdresa` INT NOT NULL AUTO_INCREMENT,
  `ulice` VARCHAR(45) NULL,
  `cislo` VARCHAR(45) NULL,
  `mesto` VARCHAR(45) NULL,
  `pocetOdjezdu` INT NULL DEFAULT 0,
  `pocetPrijezdu` INT NULL DEFAULT 0,
  `gps_lat` DOUBLE NULL,
  `gps_lgn` DOUBLE NULL,
  `poznamka` VARCHAR(160) NULL,
  PRIMARY KEY (`idAdresa`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`Misto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Misto` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Misto` (
  `idMisto` INT NOT NULL AUTO_INCREMENT,
  `idAdresa` INT NOT NULL,
  `nazev` VARCHAR(45) NULL,
  PRIMARY KEY (`idMisto`),
  INDEX `fk_Misto_Adresa1_idx` (`idAdresa` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`Smena`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Smena` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Smena` (
  `idSmena` INT NOT NULL AUTO_INCREMENT,
  `od` DATETIME(1) NULL,
  `do` DATETIME(1) NULL,
  `poznamka` VARCHAR(160) NULL,
  PRIMARY KEY (`idSmena`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`Objednavka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Objednavka` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Objednavka` (
  `idObjednavka` INT NOT NULL AUTO_INCREMENT,
  `casVytvoreni` DATETIME(1) NOT NULL,
  `casPristaveniTaxi` DATETIME(1) NOT NULL,
  `idAdresa` INT NOT NULL,
  `pocetVozu` INT NULL DEFAULT 1,
  `poznamka` VARCHAR(160) NULL,
  `uspesna` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idObjednavka`),
  INDEX `fk_Objednavka_Adresa1_idx` (`idAdresa` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`Jizda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Jizda` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Jizda` (
  `idJizda` INT NOT NULL AUTO_INCREMENT,
  `idRidic` INT NOT NULL,
  `Ridic_idOsoba` INT NOT NULL,
  `idAdresaOdkud` INT NOT NULL,
  `idAdresaKam` INT NOT NULL,
  `casStart` DATETIME(1) NOT NULL,
  `casKonec` DATETIME(1) NULL,
  `idSmena` INT NOT NULL,
  `idObjednavka` INT NULL,
  `pribliznaCena` INT NULL,
  `pocetOsob` INT NULL DEFAULT 1,
  PRIMARY KEY (`idJizda`),
  INDEX `fk_Jizda_Adresa1_idx` (`idAdresaOdkud` ASC),
  INDEX `fk_Jizda_Adresa2_idx` (`idAdresaKam` ASC),
  INDEX `fk_Jizda_Smena1_idx` (`idSmena` ASC),
  INDEX `fk_Jizda_Objednavka1_idx` (`idObjednavka` ASC),
  INDEX `fk_Jizda_Ridic1_idx` (`idRidic` ASC, `Ridic_idOsoba` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`Dochazka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Dochazka` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Dochazka` (
  `idDochazka` INT NOT NULL AUTO_INCREMENT,
  `idOsoba` INT NOT NULL,
  `prichod` DATETIME(1) NOT NULL,
  `odchod` DATETIME(1) NULL,
  PRIMARY KEY (`idDochazka`),
  INDEX `fk_Prichod_Osoba1_idx` (`idOsoba` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`LogStavu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`LogStavu` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`LogStavu` (
  `idHlaseni` INT NOT NULL AUTO_INCREMENT,
  `idOsoba` INT NOT NULL,
  `kdy` DATETIME(1) NULL,
  `poznamka` VARCHAR(160) NULL,
  `idStav` INT NOT NULL,
  PRIMARY KEY (`idHlaseni`),
  INDEX `fk_Hlaseni_Osoba1_idx` (`idOsoba` ASC),
  INDEX `fk_Hlaseni_Stav1_idx` (`idStav` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`FrontaRidicu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`FrontaRidicu` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`FrontaRidicu` (
  `idRidic` INT NULL,
  INDEX `fk_FrontaRidicu_Ridic1_idx` (`idRidic` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`RidiciVeSluzbe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`RidiciVeSluzbe` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`RidiciVeSluzbe` (
  `idRidic` INT NULL,
  INDEX `fk_RidiciVeSluzbe_Ridic1_idx` (`idRidic` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`RidiciOstatniKDispozici`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`RidiciOstatniKDispozici` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`RidiciOstatniKDispozici` (
  `idRidic` INT NULL,
  INDEX `fk_RidiciOstatniKDispozici_Ridic1_idx` (`idRidic` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`Dispecer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Dispecer` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Dispecer` (
  `idDispecer` INT NOT NULL AUTO_INCREMENT,
  `idOsoba` INT NOT NULL,
  `idStav` INT NULL,
  PRIMARY KEY (`idDispecer`),
  INDEX `fk_Dispecer_Osoba1_idx` (`idOsoba` ASC),
  INDEX `fk_Dispecer_Stav1_idx` (`idStav` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `blesk1`.`Osoba_has_Smena`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blesk1`.`Osoba_has_Smena` ;

CREATE TABLE IF NOT EXISTS `blesk1`.`Osoba_has_Smena` (
  `idOsoba` INT NOT NULL,
  `idSmena` INT NOT NULL,
  PRIMARY KEY (`idOsoba`, `idSmena`),
  INDEX `fk_Osoba_has_Smena_Smena1_idx` (`idSmena` ASC),
  INDEX `fk_Osoba_has_Smena_Osoba1_idx` (`idOsoba` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
